# Generated by Django 4.2 on 2023-05-17 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pythonapp', '0002_individuals'),
    ]

    operations = [
        migrations.DeleteModel(
            name='individuals',
        ),
    ]
